<a href="https://colab.research.google.com/github/emmanuelvaie/google_colab/blob/main/EDA_of_export_boond_database.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# @title Setup
from google.colab import auth
from google.cloud import bigquery
from google.colab import data_table

project = 'fluent-music-364313' # Project ID inserted based on the query results selected to explore
location = 'europe-west9' # Location inserted based on the query results selected to explore
client = bigquery.Client(project=project, location=location)
data_table.enable_dataframe_formatter()
auth.authenticate_user()

In [2]:
query = """
SELECT * FROM  `fluent-music-364313`.export_boond.candidates; 
"""
job = client.query(query)

## Reference SQL syntax from the original job
Use the ```jobs.query```
[method](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/query) to
return the SQL syntax from the job. This can be copied from the output cell
below to edit the query now or in the future. Alternatively, you can use
[this link](https://console.cloud.google.com/bigquery?j=fluent-music-364313:europe-west9:bquxjob_681ca93c_184a4051b54)
back to BigQuery to edit the query within the BigQuery user interface.

In [3]:
print(job.query)

SELECT * FROM  `fluent-music-364313`.export_boond.candidates;

# Result set loaded from BigQuery job as a DataFrame
Query results are referenced from the Job ID ran from BigQuery and the query
does not need to be re-run to explore results. The ```to_dataframe```
[method](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.job.QueryJob.html#google.cloud.bigquery.job.QueryJob.to_dataframe)
downloads the results to a Pandas DataFrame by using the BigQuery Storage API.

To edit query syntax, you can do so from the BigQuery SQL editor or in the
```Optional:``` sections below.

In [4]:
# Running this code will read results from your previous job
results = job.to_dataframe()
results.head()

Warning: Total number of columns (54) exceeds max_columns (20). Falling back to pandas display.

,Reference_interne,Civilite,Nom,Prenom,Type,Titre,Competences,Domaines_d_application,Formation,Experience,...,Date_de_mise_a_jour,Commentaires__informations_,Langues,Diplomes,Secteurs,Ressource___Reference_interne,Nombre_de_CV,Etape___motif,Motif___Commentaire,version
0,CAND2635,M.,Mirzaian,Vincent,Consultant Externe,EXPERT IAM,None,None,None,None,...,2023-02-24 10:32:00+00:00,None,None,2015 - ingénieurie informatique - EPITECH,None,None,1,NaN,NaN,2023-02-27 16:47:38+00:00
1,CAND2639,M.,Ben Mariem,Abderrahmen,Non défini,"Architecte, Trainer et Expert JAVA/JEE, Angula...","Java, XML, jQuery",None,None,None,...,2023-02-27 15:44:00+00:00,None,None,"ENSI - Diplôme d'ingénieur, informatique - 200...",None,None,1,NaN,NaN,2023-02-27 16:47:38+00:00
2,CAND2640,M.,SCOFFIER,Antoine,Non défini,DevOps Engineer | Freelance,"Jenkins, Python, Software craftsmanship",None,None,None,...,2023-02-27 15:46:00+00:00,None,None,"ETNA, école d'alternance en informatique - Mas...",None,None,1,NaN,NaN,2023-02-27 16:47:38+00:00
3,CAND2637,M.,ALLOUKH,Nabil,Consultant Externe,Développeur .Net senior,"angular, react, c#, f#, python, javascript, ty...",None,None,None,...,2023-02-24 16:12:00+00:00,None,Anglais (),2008 - cycle ingénierie en informatique - I.M....,None,None,1,NaN,NaN,2023-02-27 16:47:38+00:00
4,CAND2612,M.,THIERRY,Alexis,Non défini,Architect,None,None,None,None,...,2023-02-23 18:28:00+00:00,None,None,None,None,None,0,NaN,NaN,2023-02-27 16:47:38+00:00

## Show descriptive statistics using describe()
Use the ```pandas DataFrame.describe()```
[method](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html)
to generate descriptive statistics. Descriptive statistics include those that
summarize the central tendency, dispersion and shape of a dataset’s
distribution, excluding ```NaN``` values. You may also use other Python methods
to interact with your data.

In [5]:
results.describe(include='all')

Warning: Total number of columns (54) exceeds max_columns (20). Falling back to pandas display.

<ipython-input-5-f0fe35cb110e>:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  results.describe(include='all')

,Reference_interne,Civilite,Nom,Prenom,Type,Titre,Competences,Domaines_d_application,Formation,Experience,...,Date_de_mise_a_jour,Commentaires__informations_,Langues,Diplomes,Secteurs,Ressource___Reference_interne,Nombre_de_CV,Etape___motif,Motif___Commentaire,version
count,5449,5449,5449,5449,5449,5443,5243,4977,5220,5204,...,5449,250,5155,3576,4953,26,5449.000000,0.0,0.0,5449
unique,922,2,873,630,3,150,890,21,3,5,...,283,52,26,598,4,7,NaN,NaN,NaN,6
top,CAND2257,M.,A CONFIRMER,mohamed,Consultant Externe,Développeur .Net,J'attends ses dispo,"RD,Data",Master,6 à 10 ans,...,2023-02-01 09:37:00+00:00,Mobile sur IDF\nIl est d'accord pour 2 jours d...,Français (Courant),Master,Autres,COMP2592,NaN,NaN,NaN,2023-02-27 16:47:38+00:00
freq,6,5434,72,162,4425,1140,12,1026,5154,1461,...,1022,6,4656,30,4938,6,NaN,NaN,NaN,922
first,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2023-01-11 15:50:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-02-16 16:52:13+00:00
last,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2023-02-27 16:33:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-02-27 16:47:38+00:00
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.040374,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.615678,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN

In [6]:
cols = results.columns

In [7]:
import pandas as pd
prf = pd.DataFrame()

In [8]:
for c in cols:
  nb_null = results[c].isna().sum()
  freq = results[c].value_counts()
  d = pd.DataFrame(data = {'nom_col': c, 'nb_null': [nb_null], 'freq': [freq]})
  #prf = prf.append(d)
  prf = pd.concat([prf,d])

In [9]:
prf.head()

,nom_col,nb_null,freq
0,Reference_interne,0,CAND2257 6 CAND2270 6 CAND2259 6 CAND...
0,Civilite,0,"M. 5434 Mme. 15 Name: Civilite, dtyp..."
0,Nom,0,A CONFIRMER 72 SASSI 24 ZOUAOUI ...
0,Prenom,0,mohamed 162 youssef 90 hamza ...
0,Type,0,Consultant Externe 4425 Consultant Interne ...

In [10]:
nb_records = len(results)
nb_records

5449

In [11]:
prf['pct_null'] = prf['nb_null'].apply(lambda x : 100 * x/nb_records)

In [12]:
prf

,nom_col,nb_null,freq,pct_null
0,Reference_interne,0,CAND2257 6 CAND2270 6 CAND2259 6 CAND...,0.000000
0,Civilite,0,"M. 5434 Mme. 15 Name: Civilite, dtyp...",0.000000
0,Nom,0,A CONFIRMER 72 SASSI 24 ZOUAOUI ...,0.000000
0,Prenom,0,mohamed 162 youssef 90 hamza ...,0.000000
0,Type,0,Consultant Externe 4425 Consultant Interne ...,0.000000
0,Titre,6,Développeur .Net ...,0.110112
0,Competences,206,J'attends ses dispo ...,3.780510
0,Domaines_d_application,472,"RD,Data 1026 Inconnu ...",8.662140
0,Formation,229,Master 5154 Grande école 60 Bac ...,4.202606
0,Experience,245,6 à 10 ans 1461 Pas d'expérience 1...,4.496238
0,Disponibilite,151,Inconnue 3534 Immédiate 884 3 ...,2.771151
0,Outils,454,Aucun (1) ...,8.331804
0,Mobilite,478,Monde 4542 Île-de-...,8.772252
0,Etape,0,Vivier 2623 No Go Son...,0.000000
0,Evaluation_globale,226,Inconnue 3508 Non défini 922 Bon ...,4.147550
0,Provenance_CV___Type,87,LinkedIn 5226 Cooptation 134 Autre ...,1.596623
0,Provenance_CV___Detail,5324,LinkedIn 107 KHA 9 E ...,97.706001
0,Email_1,1261,info@cherryblossom.digital 72 inconnu...,23.141861
0,Email_2,5449,"Series([], Name: Email_2, dtype: int64)",100.000000
0,Email_3,5449,"Series([], Name: Email_3, dtype: int64)",100.000000
0,Telephone_1,586,06 83 34 85 63 24 0668797597 12 +3...,10.754267
0,Telephone_2,5449,"Series([], Name: Telephone_2, dtype: int64)",100.000000
0,Telephone_3,5449,"Series([], Name: Telephone_3, dtype: int64)",100.000000
0,Date_de_naissance,5125,1999-03-08 00:00:00+00:00 12 1992-11-26 00:...,94.053955
0,Nationalite,0,Française 5425 Marocaine 12 Algérien...,0.000000
0,Situation_familiale,0,"Célibataire 5449 Name: Situation_familiale,...",0.000000
0,Nombre_de_positionnements_actif,0,0 5368 1 67 2 9 8 2 4 ...,0.000000
0,Adresse,5326,10 Avenue Augustine ...,97.742705
0,Code_Postal,3944,92400.0 60 75015.0 48 78300.0 42 7501...,72.380253
0,Ville,1596,Paris 3578 Courbevoie ...,29.289778
0,Pays,0,France 4891 Maroc 276 Tunisie 21...,0.000000
0,Devise,0,"Euro 5449 Name: Devise, dtype: int64",0.000000
0,Salaire_actuel,0,0 3793 600 168 700 150 6...,0.000000
0,Salaire_brut_souhaite__fourchette____Minimum,0,0 3683 600 186 550 156 650 ...,0.000000
0,Salaire_brut_souhaite__fourchette____Maximum,0,0 4928 600 42 45000 36 4...,0.000000
0,Tarif_journalier_HT_actuel,0,0 5353 700 26 550 24 750 1...,0.000000
0,Tarif_journalier_HT_souhaite___Minimum,0,0 5172 550 54 600 38 650 3...,0.000000
0,Tarif_journalier_HT_souhaite___Maximum,0,0 5337 600 24 650 15 1000 ...,0.000000
0,Contrat,145,Freelance 4367 CDI 935 So...,2.661039
0,Responsable_manager,0,GRANMONT Léa 4936 Elidrissi Hafsa ...,0.000000
0,Responsable_RH,0,Hajiri Soumaya 1575 Elidrissi Hafsa 1...,0.000000
0,Pole,5449,"Series([], Name: Pole, dtype: int64)",100.000000
0,Agence,0,"SONATE 5449 Name: Agence, dtype: int64",0.000000
0,Date_de_creation,0,2022-02-23 00:00:00+00:00 72 2021-06-11 00:...,0.000000
0,Date_de_mise_a_jour,0,2023-02-01 09:37:00+00:00 1022 2023-02-01 0...,0.000000
0,Commentaires__informations_,5199,Mobile sur IDF\nIl est d'accord pour 2 jours d...,95.412002
0,Langues,294,Français (Courant) ...,5.395485
0,Diplomes,1873,Master ...,34.373280
0,Secteurs,496,Autres 4938 Assurance 6 Banque...,9.102588
0,Ressource___Reference_interne,5423,COMP2592 6 COMP2588 6 COMP2590 6 COMP...,99.522848
0,Nombre_de_CV,0,1 3771 0 789 2 787 3 84 4 ...,0.000000
0,Etape___motif,5449,"Series([], Name: Etape___motif, dtype: int64)",100.000000
0,Motif___Commentaire,5449,"Series([], Name: Motif___Commentaire, dtype: i...",100.000000
0,version,0,2023-02-27 16:47:38+00:00 922 2023-02-24 15...,0.000000